name: HQS build Sphinx docs for pure python repos

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  publish_documentation:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_publish_documentation_pure_python_sphinx.yml@main
    with: 
      python_folder: "."
      docs_folder: "./docs"
    secrets: inherit